
name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          # Upload the contents of the 'dist' directory to Hostinger using FTP
          # Use the GitHub secrets for FTP_SERVER and FTP_USER
          lftp -u ${{ secrets.FTP_USER }} -e "open ${{ secrets.FTP_SERVER }}; mirror -R ./dist /public_html/profile" -p 21 -d

    env:
      NODE_ENV: production
