name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build
      run: |
        rm -rf node_modules
        npm update
        npm install
        npm install @angular/compiler@11.2.14
        npm install @ng-bootstrap/ng-bootstrap@^9.1.3
        npm install --legacy-peer-deps
        ng update @angular/core
        ng version
        npx webpack
        echo "yes" | npm install -D webpack-cli
        npm audit fix
        ng build --prod
