name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Angular CLI
      run: |
        rm -rf node_modules
        npm install -g @angular/cli

    - name: Install @ng-bootstrap/ng-bootstrap
      run: npm install --legacy-peer-deps @ng-bootstrap/ng-bootstrap@^9.1.3

    - name: Build
      run: |
        npm install --legacy-peer-deps
        ng version
        npm audit fix
        ng build --prod

    
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
          server: ftp://budgetmela.com  # Your Hostinger FTP server
          username: ${{ secrets.FTP_USER }}  # Your GitHub secret for FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # Your GitHub secret for FTP password
          local-dir: ./dist/  # The directory with your built Angular project
          remote-dir: /public_html/profile/  # The target directory on your Hostinger server
